version: "3.3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apna_job_development
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000" 
    environment:
      RAILS_ENV: development